/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: iSteven (https://sketchfab.com/OneSteven)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bell-h-13-6ec8c4b7f9124884866a5c4fbcc2ee65
Title: Bell H-13
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import heliscene from "../assets/3d/helicopter.glb";

export function Helicopter(props) {
  const { nodes, materials } = useGLTF(heliscene);

  return (
    <group {...props} dispose={null}>
    <group position={[1, 0, 0]} scale={1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_Material001_0.geometry}
          material={materials["Material.001"]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh001_glass_0.geometry}
          material={materials.glass}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_prop_0.geometry}
          material={materials.prop}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_paint_0.geometry}
          material={materials.paint}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh004_strut_0.geometry}
          material={materials.strut}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh005_pipe_0.geometry}
          material={materials.pipe}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh006_Material002_0.geometry}
          material={materials["Material.002"]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh007_Blinds_Roman_Hobbled_Blue_0.geometry}
          material={materials.Blinds_Roman_Hobbled_Blue}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh008_copper_0.geometry}
          material={materials.copper}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh009_Color_001_0.geometry}
          material={materials.Color_001}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload(heliscene);
