/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: commonfactory (https://sketchfab.com/commonfactory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/night-sky-visible-spectrum-monochromatic-cfb156f03a7341b8a0a0ba0445ca742d
Title: Night Sky Visible Spectrum Monochromatic
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import scene  from '../assets/3d/night.glb';
import * as THREE from 'three';
export function Night(props) {
  const { nodes, materials } = useGLTF(scene);
  return (
    <group {...props} dispose={null}>
     <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.material}
            position={[-5, -3.321, -0.134]}
            rotation={[0.354, -0.348, -3.024]}
            scale={0.1000}
           
          />
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Material}
            rotation={[0.436, -0.415, 0.175]}
            scale={100}
            material-side={THREE.DoubleSide} 

          /> */}
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials["Material.001"]}
            rotation={[0.376, -1.085, 0.524]}
            scale={100}
            material-side={THREE.DoubleSide} 

          /> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(scene);
